name: Deploy to Deta
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: HarshKapadia2/deta-deploy@v1.0.2
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'cubix-backend'
          deta-project: 'cubix-backendlol'
