on: [push,workflow_dispatch]

env:
  GIT_COMMIT_SHA: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses: actions/checkout@v2
      - name: install and new
        run: |
          curl -fsSL https://get.deta.dev/cli.sh | sh
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}
          ~/.deta/bin/deta new --python cubixolo
      - name: deploy
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }}
          deta-name: 'cubixx'
