name: Deploy to Deta
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses: actions/checkout@v2 
      - name : new micro
        run: |
         curl -fsSL https://get.deta.dev/cli.sh | sh
         export PATH="/home/runner/.deta/bin:$PATH"
         export DETA_ACCESS_TOKEN= ${{ secrets.DETA_ACCESS_TOKEN }}
         deta auth disable
         deta login
      - name : deploy
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with: 
          deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }}
          deta-name: 'cubixx'
          deta-project: 'cubixx'
      
