name: Deploy to Deta
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses: actions/checkout@v2 
      - name : deploy
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with: 
          deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }}
          deta-name: 'cubixx'
          deta-project: 'cubixx'
      
